-d C:\Users\wyc\Desktop\uart_zyh4\uart_zyh\impl\gwsynthesis\uart_zyh.vg
-p GW2A-18-PBGA484-8
-pn GW2A-LV18PG484C8/I7
-cst C:\Users\wyc\Desktop\uart_zyh4\uart_zyh\src\uart.cst
-cfg C:\Users\wyc\Desktop\uart_zyh4\uart_zyh\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
